name: "Deploy static website"
description: "Deploy a static website for GitHub pages"

inputs:
  deploy_dir:
    description: "Directory to deploy"
    required: true
  github_token:
    description: "GitHub token used to push the site"
    required: true

runs:
  using: docker
  image: Dockerfile
